# Generated by Django 4.2.6 on 2023-10-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_Id', models.IntegerField()),
                ('prod_Name', models.CharField(max_length=255)),
                ('Prod_Price', models.IntegerField()),
                ('Prod_Desc', models.CharField(max_length=255)),
                ('Prod_image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
