# Generated by Django 4.2.6 on 2023-10-18 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tel_number', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('destic', models.CharField(max_length=255)),
                ('conform_Password', models.CharField(max_length=255)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
