# Generated by Django 4.2.6 on 2023-10-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registermodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodels',
            name='conform_Password',
        ),
    ]
